### ISSUE TITLE
Script no longer works

### ISSUE THREAD

**Issue by dalewkim** [uclobby/Get-TeamsVersion#1] opened 2021-10-21 16:54 UTC
Get-Content $env:UserProfile"\AppData\Roaming\Microsoft\Teams\settings.json" | ConvertFrom-Json

Results in:

ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 'enableIpsForCallingContext' and

**Comment by uclobby** [comment] 2021-10-22 15:13
What is your teams version? I just tested again with the current version and it worked.

**Comment by uclobby** [comment] 2022-02-11 20:46
The issue is fixed in 1.2

**Closed as completed by uclobby** 2022-02-11 20:46 UTC
